version: '3.10'
services:
  django:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/code
    command: /bin/sh -c "cd /code/mysite; python manage.py migrate; python manage.py runserver 0:8000"
    #command: /bin/sh -c "cd /code/mysite; python manage.py migrate; python manage.py test chat.tests"
    ports:
      - 8000:8000
    depends_on:
      - redis
  redis:
    image: redis:5
    ports:
      - 6379:6379
    tty: true
